[tox]
envlist = py{39,310,311,312,313,314}-{linux,macos}

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos

[testenv]
commands =
    python --version
    coverage run -m unittest discover tests
    pyflakes iddiff tests
deps =
    .[tests]
allowlist_externals =
    coverage
    pyflakes
